---
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types:
      - closed
      - opened
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: "teste"
    outputs:
      bats_version: ${{ steps.bat_version.outputs.test }}
    steps:
      - id: informations
        run: |
          echo $GITHUB_REF
          echo $GITHUB_SHA
          echo ${{github.base_ref}}
          echo ${{github.head_ref}}
